#version: '3'
#
#
#services:
#  app-server:
#    container_name: server_jira
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: jira-app
#    ports:
#      - "8080:8080"
#
#  postgres:
#    container_name: db_jira
#    image: postgres:latest
#    expose:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: jira
#      POSTGRES_PASSWORD: JiraRush
#      POSTGRES_DB: jira
#
#
##  nginx:
##    container_name: nginx_jira
##    image: nginx
##    ports:
##      - "80:80"
##    volumes:
##      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
##    depends_on:
##      - app-server
##    networks:
##      - jirarush-network
#
